name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CICD_ASSIGN }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/github-actions-assign/cloud-run-cicd/cloud-run-cicd .
          docker push us-central1-docker.pkg.dev/github-actions-assign/cloud-run-cicd/cloud-run-cicd

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-run-cicd \
            --image us-central1-docker.pkg.dev/github-actions-assign/cloud-run-cicd/cloud-run-cicd \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
